services:
  central:
    image: ${CANTON_IMAGE:-digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.6.3}
    container_name: central
    ports:
      - "4011:4011"
      - "5011:5011"
    volumes:
      - "./config/central:/config"
      - "./.migration:/migration"
      - "./.daml/dist:/dars"
    tty: true
    stdin_open: true
    command:
      - "--config"
      - "/config/canton.conf"
      - "--bootstrap"
      - "/config/canton.bootstrap"
    depends_on:
      central-database:
        condition: service_healthy
      domain:
        condition: service_started
  central-database:
    image: "${POSTGRES_IMAGE:-postgres:14.7}"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=central
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "central"]
      interval: 1s
  traderOne:
    image: ${CANTON_IMAGE:-digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.6.3}
    container_name: traderOne
    ports:
      - "4021:4021"
      - "5021:5021"
    volumes:
      - "./config/traderOne:/config"
      - "./.migration:/migration"
      - "./.daml/dist:/dars"
    tty: true
    stdin_open: true
    command:
      - "--config"
      - "/config/canton.conf"
      - "--bootstrap"
      - "/config/canton.bootstrap"
    depends_on:
      traderOne-database:
        condition: service_healthy
      domain:
        condition: service_started
      central:
        condition: service_started
  traderOne-database:
    image: "${POSTGRES_IMAGE:-postgres:14.7}"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=traderOne
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "traderOne"]
      interval: 1s

  domain:
    image: ${CANTON_IMAGE:-digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:latest}
    ports:
      - "4001:4001"
    volumes:
      - "./config/domain:/config"
    command:
      - "daemon"
      - "--config"
      - "/config/canton.conf"
      - "--bootstrap"
      - "/config/canton.bootstrap"
    depends_on:
      domain-database:
        condition: service_healthy
  domain-database:
    image: "${POSTGRES_IMAGE:-postgres:14.7}"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=domain
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "domain"]
      interval: 1s
